<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container73OkRNg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container73OkRNg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container73OkRNg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container73OkRNg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container73OkRNg\App_KernelDevDebugContainer([
    'container.build_hash' => '73OkRNg',
    'container.build_id' => '59ff00f3',
    'container.build_time' => 1583843790,
], __DIR__.\DIRECTORY_SEPARATOR.'Container73OkRNg');
